name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    


jobs:
  build:

    windows:
    timeout-minutes: 10

    strategy:
      matrix:
        os: [windows-latest, windows-2016]
        toolset: [clang-cl, default]
        include:
          - toolset: clang-cl
            toolset_option: -T"ClangCl"
        exclude:
          - os: windows-2016
            toolset: clang-cl
     runs-on: ${{ matrix.os }}
     
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.9'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        dir: '${{ github.workspace }}/example/'
        install-deps: 'true'
        modules: 'qtcharts qtwebengine'
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
        cached: 'false'
        aqtversion: '==0.9'
        py7zrversion: '==0.7'
        extra: '--external 7z'
    - name: cmake generate
      run: mkdir build && cd build && cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: cmake build
      run: cmake --build . -j 4

    
